In [7]:
# for CF
import pandas as pd
import numpy as np
import time
from sklearn import cross_validation as cv
from sklearn import preprocessing
from operator import itemgetter
from collections import OrderedDict
from sklearn.preprocessing import StandardScaler
from numpy import *

C:\Users\kami\Anaconda3\envs\data_sciense\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [13]:
# read data
file_name = 'ratings.data'
with open(file_name,'r') as f:
    data = [x.strip().split('\t') for x in f]
user_id = [item[0] for item in data]
item_id = [item[1] for item in data]
rating = [item[2] for item in data]
time_stamp = [item[3] for item in data]

df = pd.DataFrame(
    {'user_id': user_id,
     'item_id': item_id,
     'rating': rating
    })

In [14]:
all_user_id = pd.unique(df['user_id']).tolist()
all_item_id = pd.unique(df['item_id']).tolist()

In [22]:
user_1_df = df.loc[df['user_id'] == all_user_id[0]]
user_2_df = df.loc[df['user_id'] == all_user_id[1]]

In [120]:
user_1_df
ru = []
rv = []

for i in range(len(all_item_id)):
    if all_item_id[i] in list(user_1_df['item_id']):
        match = user_1_df.loc[user_1_df['item_id'] == all_item_id[i]]['rating'].values[0]
        ru.append(match)
    else:
        ru.append('0')
        
    if all_item_id[i] in list(user_2_df['item_id']):
        match = user_2_df.loc[user_2_df['item_id'] == all_item_id[i]]['rating'].values[0]
        rv.append(match)
    else:
        rv.append('0')

In [61]:
user_1_df = df.loc[df['user_id'] == all_user_id[0]]
user_2_df = df.loc[df['user_id'] == all_user_id[1]]
match_list = list(set(user_1_df['item_id']).intersection(user_2_df['item_id']))
match_list
ru = user_1_df.loc[user_1_df['item_id'].isin(match_list)].sort_values('item_id')['rating']
rv = user_2_df.loc[user_2_df['item_id'].isin(match_list)].sort_values('item_id')['rating']
ru = np.asarray(list(map(int, ru)))

array([2, 3, 4])

In [225]:
# create function for cauculating sim by U-CF-pcc and U-CF-cos
def user_sim(df, cos_pcc, user_1, user_2):
    all_user_id = pd.unique(df['user_id']).tolist()
    all_item_id = pd.unique(df['item_id']).tolist()
    
    user_1_df = df.loc[df['user_id'] == user_1]
    user_2_df = df.loc[df['user_id'] == user_2]
    
    ru = [0] * len(all_item_id)
    rv = [0] * len(all_item_id)
    
    pos_1 = [all_item_id.index(i) for i in user_1_df['item_id']]
    pos_2 = [all_item_id.index(i) for i in user_2_df['item_id']]
    for i in range(len(pos_1)):
        ru[pos_1[i]] = user_1_df['rating'].values[i]
    for i in range(len(pos_2)):
        rv[pos_2[i]] = user_2_df['rating'].values[i]
    
    ru = np.asarray(list(map(int, ru)))
    rv = np.asarray(list(map(int, rv)))
    
    if cos_pcc == 'cos':
        vector_len = np.sqrt(ru.dot(ru)) * np.sqrt(rv.dot(rv))
        return np.dot(ru, rv) / vector_len
    elif cos_pcc == 'pcc':
        match_pos = []
        for i in range(len(ru)):
            if ru[i] != 0 and rv[i] != 0:
                match_pos.append(i)
                
        match_ru = ru[match_pos]
        match_rv = rv[match_pos]
        print(match_ru)
        print(match_rv)
        numerator = np.dot(match_ru - np.average(match_ru), match_rv - np.average(match_rv))
        denominator = np.sqrt(np.sum(np.power(match_ru - np.average(match_ru), 2))) * np.sqrt(np.sum(np.power(match_rv - np.average(match_rv), 2)))
        
        if denominator == 0:
            return 0
        else:
            return numerator / denominator

In [226]:
user_sim(df, 'pcc', all_user_id[0], all_user_id[40])

[5 4 3 3]
[4 4 4 4]
<class 'numpy.float64'>


0

In [228]:
print("abc " + str(3/4))

abc 0.75


In [4]:
a = [1,2,3,4]
b = [5,6,7,8]
c = pd.DataFrame({
    'a' : a,
    'b' : b
})
print(c)

   a  b
0  1  5
1  2  6
2  3  7
3  4  8


In [ ]:
a=[1,2,3,4]#列表a
b=[5,6,7,8]#列表b
c={"a" : a,
   "b" : b}#将列表a，b转换成字典
data=DataFrame(c)#将字典转换成为数据框
print(data)

In [179]:
import numpy as np
from sklearn import preprocessing
 
# Two samples, with 3 dimensions.
# The 2 rows indicate 2 samples, 
# and the 3 columns indicate 3 features for each sample.
X = np.asarray([[-1,0,1],
                [0,1,2]], dtype=np.float) # Float is needed.
 
X = np.matrix(X)
print(X)
X_normalized = preprocessing.normalize(X, norm='l2', axis = 1)

from numpy import *
X = X - mean(X, axis=0)
print(X)
print(preprocessing.normalize(X, norm='l2', axis = 0))

[[-1.  0.  1.]
 [ 0.  1.  2.]]
[[-0.5 -0.5 -0.5]
 [ 0.5  0.5  0.5]]
[[-0.70710678 -0.70710678 -0.70710678]
 [ 0.70710678  0.70710678  0.70710678]]


In [173]:
np.sqrt((1+4+9+16)/8)

1.9364916731037085

In [125]:

find = lambda searchList, elem: [[i for i, x in enumerate(searchList) if x == e] for e in elem]
for i in range(len(all_user_id)):
    temp_rating_list = np.array([0] * len(all_item_id))
    pos = find(all_item_id, df.loc[df['user_id'] == all_user_id[i]]['item_id'].values.tolist())
    pos = [y for x in pos for y in x]
    temp_rating_list[pos] = df.loc[df['user_id'] == all_user_id[i]]['rating'].values.tolist()

    user_item_mat.append(temp_rating_list)
user_item_mat = np.matrix(user_item_mat)

In [129]:
user_item_mat.T.dot(user_item_mat)

matrix([[1979, 1053,    2, ...,   12,   12,   12],
        [1053, 5360,   34, ...,   12,   12,   12],
        [   2,   34,   74, ...,    0,    0,    0],
        ...,
        [  12,   12,    0, ...,    9,    9,    9],
        [  12,   12,    0, ...,    9,    9,    9],
        [  12,   12,    0, ...,    9,    9,    9]])

In [120]:
np.asarray(user_item_mat).shape

(943, 1682)

In [88]:
a = [1,2,3,4]
b = [5,6,7,8]
c = []
c.append(a)
c.append(b)
np.asarray(c)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [97]:
a = [1,2,3,4]
b = [0,1,9,7,8,4,5,6,3,10,2]

matches = [item for item in a if item in b]
matches

[1, 2, 3, 4]

In [11]:
b=np.mat('1 2; 3 4')
print(b)
b=preprocessing.normalize(b , norm='l2', axis = 1)
print(b)
1/sqrt(10)

[[1 2]
 [3 4]]
[[0.4472136  0.89442719]
 [0.6        0.8       ]]


0.31622776601683794

In [14]:
import numpy as np
a = 3
b = 4
np.multiply(a,b)

12

In [17]:
a = 1
a += 3
a

4